theme: jekyll-theme-minimal
title: Cheltenham Coronavirus Summary (covid19)
description: "An archive of covid data from coronavirus.gov.uk for the lower tier government area of Cheltenham, in Gloucestershire. Using a scheduled github-action to run some python that saves corona.json file once a day. A further python script updates this readme with summary statistics"
logo:
show_downloads: false
markdown: kramdown